export const BEGIN_AJAX_CALL = 'BEGIN_AJAX_CALL';
export const AJAX_CALL_ERROR = 'AJAX_CALL_ERROR';

export const LOAD_ARTISTS_SUCCESS = 'LOAD_ARTISTS_SUCCESS';
export const CREATE_NEW_REGISTER_SUCCESS = 'CREATE_NEW_REGISTER_SUCCESS';
export const CREATE_NEW_REQUIREMENT_SUCCESS = 'CREATE_NEW_REQUIREMENT_SUCCESS';

